### ISSUE TITLE
heartbeat API returns 500 internal status error

### ISSUE THREAD

**Issue by cfreeman** [MeasureTheFuture/mothership_beta#1]
mothership log contains:

2016-01-27 01:52:16,489 ERROR django.request[handle_uncaught_exception]: Internal Server Error: /scout_api/heartbeat/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/www-data/mothership_beta/mothership_beta/scout_api/views.py", line 30, in dispatch
    return super(ApiPOSTMixin, self).dispatch(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/www-data/mothership_beta/mothership_beta/scout_api/views.py", line 252, in post
    json_data = json.loads(attachment)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

**Comment by cfreeman** [comment]
Looking at the logs a little more, it appears as though the mothership is treating the name of the attachment as the content. 

/scout_api/<uuid>/log returns 200 OK. But in the mothership logs the content of the file is:

INFO mothership_beta.scout_api.views[post]: Log data received from scout Scout #1. Data as follows: scout.log

Rather than the content of scout.log. I'm guessing it is the if statement in def _get_request_attachment that treats FILES differently from POST?

**Comment by cfreeman** [comment]
Starting with a file named scout.log and containing the following text:
```
2016/01/29 09:42:54 INFO: Starting scout.
2016/01/29 09:43:09 INFO: Starting measure
```

The following curl command reproduces the log issue:

```
$ curl -F "scout.log=@scout.log" 10.1.1.6/scout_api/800fd548-2d2b-4185-885d-6323ccbe88a0/log/
Roger that logfile, Scout!
```

However the mother ship log reads:

```
2016-02-03 00:00:30,518 INFO mothership_beta.scout_api.views[post]: Log data received from scout Scout #1. Data as follows: scout.log
```

While I was expecting it to contain:
```
2016-02-03 00:00:30,518 INFO mothership_beta.scout_api.views[post]: Log data received from scout Scout #1. Data as follows: 2016/01/29 09:42:54 INFO: Starting scout.
2016/01/29 09:43:09 INFO: Starting measure
```

**Comment by cfreeman** [comment]
Starting with a file named 'heartbeat.json' and containing the following text:

```
{
        "UUID":"800fd548-2d2b-4185-885d-6323ccbe88a0",
        "Version":"0.1",
        "Health":{
            "IpAddress":"10.1.1.1",
            "CPU":0.4,
            "Memory":0.1,
            "TotalMemory":1233312.0,
            "Storage":0.1
        }
}
```

The following curl command reproduces the heartbeat issue:

```
$ curl -F "heartbeat.json=@heartbeat.json" 10.1.1.6/scout_api/heartbeat/
<h1>Server Error (500)</h1>
```

While the mothership log contains the the error mentioned above.
