### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by cfreeman** [MeasureTheFuture/mothership_beta#5]
When running the mothership on an Intel Edison (no sample data, just an empty/fresh install), mothership_beta.log contains the following error message:

2016-05-15 03:54:20,789 ERROR django.request.tastypie[_handle_500]: Internal Server Error: /graphs/v1/clockgraphpeoplecount/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 433, in dispatch_list
    return self.dispatch('list', request, **kwargs)
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 465, in dispatch
    response = method(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 1302, in get_list
    return self.create_response(request, to_be_serialized)
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 1202, in create_response
    serialized = self.serialize(request, data, desired_format)
  File "/www-data/mothership_beta/mothership_beta/graphs/resources.py", line 336, in serialize
    data = self._aggregate(data)
  File "/www-data/mothership_beta/mothership_beta/graphs/resources.py", line 325, in _aggregate
    for i in range(len(bucketed_data[0]))]
IndexError: list index out of range

**Comment by thatandromeda** [comment]
I decided tastypie was the wrong way to build this API and have entirely ripped out the code in question.
