### ISSUE TITLE
FAIL: test_response (mothership_beta.scout_api.tests.test_helpers.MeasureStartGETTest)

### ISSUE THREAD

**Issue by cfreeman** [MeasureTheFuture/mothership_beta#9]
When running the test suite, the following failure is encountered:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/Users/cfreeman/Projects/measure-the-future/code/mothership_beta/mothership_beta/scout_api/tests/test_helpers.py", line 91, in test_response
    self._get_endpoint()
AssertionError: ScoutAPIException not raised

**Comment by cfreeman** [comment]
Actually. Don't think I have this one yet.
